site:
  name: Nomad Life
  site: 'https://nomad.danieleghidoli.it'
  base: '/'
  trailingSlash: false
  logo: ~/assets/images/logo.png
  home:
    title: Hi, I'm Daniele. <br/>Web Developer and Digital Nomad
    subtitle: Here I share some tips and experiences about my travels and my nomad life around the World
    cover: ~/assets/images/cover.jpg
  
# Default SEO metadata
metadata:
  title:
    default: Daniele Ghidoli - Nomad Life
    template: '%s — Nomad Life'
  description: "Life is Just a Trip. Here I share some tips and experiences about my travels and my nomad life around the World"
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Nomad Life - Life is Just a Trip
    images:
      - url: '~/assets/images/cover.jpg'
        width: 2000
        height: 1336
    type: website
  twitter:
    handle: '@ghidoz'
    site: '@ghidoz'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%year%/%month%/%day%/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: '' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: 'G-03Q07P1G9F'

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
